server:
  port: 8082
  tomcat:
   uri0-encoding: UTF-8
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.210:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: spring-user
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    mode: HTML5
    suffix: .html
  mvc:
    static-path-pattern: /static/**
    # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/