
server:
  port: 8092
spring:
  application:
    name: service-feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

