server:
  port: 8094
  timeout: 10
  tomcat:
   uri0-encoding: UTF-8

spring:
  application:
    name: spring-gateway-admin
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.244:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/database
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      pool:
        max-idle: 30
        min-idle: 10
        max-active: 30
        max-wait: 10000
  rabbitmq:
    host=localhost: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
#  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: test.model
#  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml
#  多层级目录  mapper-locations: classpath:mapper/**/**.xml
