server:
  port: 8081
  timeout: 10
  tomcat:
   uri0-encoding: UTF-8

spring:
  application:
    name: server-db
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbtest
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

    
mybatis:
#  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: test.model
#  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml
#  多层级目录  mapper-locations: classpath:mapper/**/**.xml